const LANGUAGE_ICONS: Readonly<Record<string, string>> = {
  typescript: "",
  ts: "",
  tsx: "",
  javascript: "",
  js: "",
  jsx: "",
  node: "",
  python: "",
  py: "",
  go: "",
  golang: "",
  rust: "",
  rs: "",
  java: "",
  html: "",
  css: "",
  scss: "",
  sass: "",
  json: "",
  jsonc: "",
  bash: "",
  shell: "",
  sh: "",
  zsh: "",
  fish: "",
  text: "󰈙",
  txt: "󰈙",
  plaintext: "󰈙",
  plain: "󰈙",
  markdown: "",
  md: "",
  yaml: "",
  yml: "",
  dockerfile: "",
  docker: "",
  sql: "",
  c: "",
  cpp: "",
  "c++": "",
  cxx: "",
  csharp: "󰌛",
  "c#": "󰌛",
  cs: "󰌛",
  kotlin: "",
  kt: "",
  swift: "",
  dart: "",
  lua: "",
  ruby: "",
  rb: "",
  php: "",
  vue: "",
  svelte: "",
  react: "",
  reactjs: "",
};

export const GENERIC_CODE_ICON = "";

export function getLanguageIcon(language: string): string | undefined {
  return LANGUAGE_ICONS[language.trim().toLowerCase()];
}
